### ISSUE TITLE
update api_key length validation

### ISSUE THREAD

**Issue by SowmyaCVBS** [s1-howie/s1-agents-helper#10]
I believe the API_key length has beewn updated from 80 to 422, install script validation fails wherever api_key length validation is added.

**Comment by ccincotti3** [comment]
+1

**Comment by s1-howie** [comment]
Apologies for the late reply!  I've updated the API_KEY length checks to look for values greater than 79 characters.

NOTE:  This repository will soon be deprecated as these scripts are being moved to another [repo](SentinelOne's S1Community) on SentinelOne's S1Community GitHub.
